#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
 -v app_password="$APP_DB_PASSWORD" -v worker_password="$WORKER_DB_PASSWORD" <<'SQL'
CREATE ROLE mail_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS PASSWORD :'app_password';
CREATE ROLE mail_worker LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE BYPASSRLS PASSWORD :'worker_password';
CREATE DATABASE selfmail_test;
SQL
