#!/bin/sh
set -eu
test -z "$(gofmt -l cmd internal pkg)" || { echo 'Run gofmt before verification' >&2; exit 1; }
go mod verify
go test -race -count=1 ./...
go vet ./...
go build ./cmd/...
go run golang.org/x/vuln/cmd/govulncheck@v1.8.0 ./...
